#-------------------------------
# General Site Settings

title: Jack Roper
logo: "assets/images/logo/logo-1.png"
author: themefisher
description: Jack Roper personal website
email: jackwesleyroper@gmail.com
#phone: 
#address: 
#copyright:

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Currently under development!

social:
- {icon: "ti-linkedin", link: "https://www.linkedin.com/in/jwroper/"}
- {icon: "ti-github", link: "https://github.com/jackwesleyroper"}
- {icon: "ti-twitter", link: "https://twitter.com/jackwesleyroper"}
- {icon: "ti-facebook", link: "https://www.facebook.com/jackwesleyroper"}
- {icon: "ti-instagram", link: "https://www.instagram.com/jackwesleyroper/"}
- {icon: "ti-youtube", link: "https://www.youtube.com/channel/UCBqLQLU_ntpev_Fw6SqcrWg"}
- {icon: "ti-soundcloud", link: "https://soundcloud.com/jwroper"}



#-------------------------------
# About (Section and Page)

# About Section
blurb:
 An experienced IT professional focused on Cloud Technologies and DevOps, continually updating and improving my skills to keep pace with an ever changing industry.
blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Charlotte Roper"
    image : "assets/images/team/member-1.jpg"
    designation : "Wife"
    
#  - title : "Julias Carlie"
#    image : "assets/images/team/member-2.png"
#    designation : "Web Developer"
    
#  - title : "John Doe"
#    image : "assets/images/team/member-3.png"
#    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Cloud, color: '#fdb157', value: '90%'}
- {name: Microsoft Azure, color: '#007fff', value: '90%'}
- {name: DevOps, color: '#9473e6', value: '60%'}
- {name: Amazon AWS, color: '#FF9900', value: '50%'}
- {name: Guitar, color: '#bdecf6', value: '80%'}
- {name: Drums, color: '#bdecf6', value: '45%'}
- {name: Mountain Biking, color: '#bdecf6', value: '70%'}
- {name: Pedal Building, color: '#bdecf6', value: '75%'}
- {name: Cricket, color: '#bdecf6', value: '50%'}

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Lead Consultant Specialist (Microsoft Azure), icon: 'icon-1.png', date: 'Jan 2019 - Present', organization: 'BT'}
- {name: Systems Cloud Operations Engineer, icon: 'icon-2.png', date: 'May 2016 - April 2019', organization: 'Solarvista Software'}
- {name: I.T. Infrastructure Technician, icon: 'icon-3.png', date: 'Nov 2014 - May 2016', organization: 'Spear & Jackson Group'}
- {name: Network Infrastructure Engineer, icon: 'icon-1.png', date: 'Apr 2007 - Nov 2014', organization: 'Imagesound'}
- {name: Senior I.T. Technician, icon: 'icon-2.png', date: 'Jul 2005 - Apr 2007', organization: 'Euro Dismantling Services'}
- {name: PC Support Analyst, icon: 'icon-3.png', date: 'Jul 2003 - Jul 2004', organization: 'BPB (British Gypsum)'}

#-------------------------------
# Education Section

education-title: Education & Qualifications
education:
- {name: BSc Hons - Computing (Networks), date: '2005', organization: 'Sheffield Hallam University'}
- {name: Azure Solutions Architect, date: '2021', organization: 'Microsoft'}
- {name: Azure DevOps Engineer, date: '2020', organization: 'Microsoft'}
- {name: Azure Administrator, date: '2020', organization: 'Microsoft'}
- {name: Azure Security Administrator, date: '2021', organization: 'Microsoft'}
- {name: Solutions Architect Associate, date: '2020', organization: 'AWS'}
- {name: Terraform Associate, date: '2020', organization: 'Hashicorp'}
- {name: 365 Security Administration, date: '2019', organization: 'Microsoft'}

#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: Guitar Pedal Building,
    icon: ti-palette,
    description: 'Need a guitar pedal? Check out the Red Mist Effects section!',
    active: true # Add true to select section
  }
#- {
#    name: UX Design,
#    icon: ti-vector,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: true # Add true to select section
#  }
#- {
#    name: Interaction Design,
#    icon: ti-panel,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: # Add true to select section
#  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Charlotte Roper"
    image: "assets/images/testimonial/client-1.jpg"
    designation : "Wife"
    content : "Jack is the best Husband i've ever had!"
    
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: jackwesleyroper@gmail.com
